export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const REMOVE_PARTICIPANT = 'REMOVE_PARTICIPANT';
export const CHECK_FORM_VALIDITY = 'CHECK_FORM_VALIDITY';

export const DATE = 'DATE';
export const LOCATION = 'LOCATION';
export const AMMOUNT = 'AMMOUNT';

export const HOST_NAME = 'HOST_NAME';
export const HOST_EMAIL = 'HOST_EMAIL';

export const SET_PARTICIPANTS = 'SET_PARTICIPANTS';
